#!/bin/bash
# Script 1: System Identity Report
# Author: Ayan Tandon
# Software: Python

STUDENT_NAME="Ayan Tandon"
SOFTWARE_CHOICE="Python"

KERNEL=$(uname -r)
USER_NAME=$(whoami)
HOME_DIR=$HOME
CURRENT_DATE=$(date)
UPTIME=$(uptime -p)

echo "======================================="
echo "Open Source Audit - $STUDENT_NAME"
echo "======================================="
echo "Chosen Software : $SOFTWARE_CHOICE"
echo "User Name       : $USER_NAME"
echo "Home Directory  : $HOME_DIR"
echo "Kernel Version  : $KERNEL"
echo "System Uptime   : $UPTIME"
echo "Current Date    : $CURRENT_DATE"
echo "======================================="
