#!/bin/bash
# Script 2: FOSS Package Inspector
# Author: Ayan Tandon

PACKAGE="python"

echo "======================================="
echo " FOSS PACKAGE INSPECTOR "
echo "======================================="

# Check if Python exists
if command -v $PACKAGE >/dev/null 2>&1
then
    echo "$PACKAGE is installed."
    echo "Version:"
    $PACKAGE --version
else
    echo "$PACKAGE is NOT installed."
fi

echo ""
echo "PHILOSOPHY NOTE"
echo "----------------"

case $PACKAGE in
    python)
        echo "Python: a language built for readability and open collaboration."
        ;;
    git)
        echo "Git: version control supporting distributed development."
        ;;
    vlc)
        echo "VLC: open-source media player supporting many formats."
        ;;
    *)
        echo "Unknown package."
        ;;
esac
